### ISSUE TITLE
Can not install this package

### ISSUE THREAD

**Issue by mialex** [Setasign/SetaFPDF#18]
Hello, we have bought  the SetaPDF-Core and I'm trying to install this package, but it gives me an error because the composer tries to install the next:

**Installing setasign/eval/setapdf-core/ioncube (1.0.2237252): Downloading (failed)**

and we get

```
  [Composer\Downloader\TransportException]
  The "https://www.setasign.com/downloads/eval/{someId}/ioncube/SetaPDF-Core-License.zip" file could not be downloaded (HTTP/1.1 404 Not Found)
```

We have the latest core version.

And could you let me know if with this library we can work with utf-8 text and fonts?

**Comment by JanSlabon** [comment]
It looks like you are still having a dependency to an evaluation version of the SetaPDF-Core component in your composer.json. Can you show it? Currently I cannot find a valid license in your account at our website. Could you tell me the licensee name (if you want to keep it confidential, feel free to send us an email at support@setasign.com).

And: Yes, you can use UTF-8 and external TTF fonts (RTL and special scripts are not supported) with this library while using the same interface as you know from FPDF.

**Comment by mialex** [comment]
Hello, sorry, my fault. I was installing the evaluation version. I've installed master and it works now. Thank you!
