### ISSUE TITLE
Composer download throttling recommendations

### ISSUE THREAD

**Issue by pabloolvcastro** [Setasign/SetaFPDF#27]
Hi Dear Maintainers,

We currently use your application solution `setapdf-stampe` and ran into a throttling limitation. What would be the recommendation to download the library? We're using the composer reference as recommended in this repository.

**Error details**
> In CurlDownloader.php line 617:
>                                                                                
>   The "https://www.setasign.com/downloads/2854243/SetaPDF-Core_2.36.0.1597-without-demos.zip" file could not be downloaded (HTTP/1.1 429 You have downloaded more than 200 files! Please wait 24 hours to download more.)            

**Composer reference**
```json
"setasign/setapdf-stamper": "2.36.0.1597"
...
"repositories": [
        {
            "type": "composer",
            "url": "https://www.setasign.com/downloads/"
        }
    ],
```

**Comment by JanSlabon** [comment]
Please contact us at support@setasign.com regarding that issue and send us the email address you're using to authenticate at our repository so that we can adjust the threshold in your profile for you.
